graphhopper:
  datareader.file: /data/finland-latest.osm.pbf
  graph.location: /data/graph-cache

  graph.elevation.provider: gmted
  graph.elevation.cache_dir: /data/elevation-cache
  graph.elevation.dataaccess: MMAP

  graph.encoded_values: average_slope, surface, road_environment

  import.osm.ignored_highways: motorway,trunk

  profiles:
    - name: bike
      custom_model_files: [bike-base.json]

  custom_model_folder: /graphhopper/custom_models

server:
  application_connectors:
    - type: http
      port: 8989
      bind_host: 0.0.0.0
  request_log:
    appenders: []
